# This file is part of luducat. License: GPL-3.0-or-later. Contact: luducat@trinity2k.net
# amazon_session.py

# Protocol documented from Nile (https://github.com/imLinguin/nile)
# Copyright (c) imLinguin and Nile contributors
# Licensed under GPLv3
# Clean-room implementation from analysis notes; endpoint constants and
# request field names are functional facts required by the Amazon API.
"""Amazon Games device-auth session manager.

Amazon has no public OAuth client — the app registers itself as a
"device" (the Amazon Games launcher identity) via OpenID 2.0 + PKCE:

    1. Generate a PKCE pair and a device identity (serial + client_id)
    2. User completes the sign-in URL in a browser (password + OTP +
       transaction approval — Amazon forces this for device_auth_access,
       cookies alone never suffice)
    3. The redirect lands on amazon.com carrying a single-use
       ``openid.oa2.authorization_code`` query parameter
    4. POST /auth/register exchanges it for bearer + refresh tokens
    5. The refresh token renews silently thereafter

The registered identity (serial + client_id) must be persisted for the
lifetime of the registration — it travels with the tokens in one
keyring blob.
"""

from __future__ import annotations

import base64
import hashlib
import logging
import secrets
import time
import uuid
from typing import Any, Callable, Dict, Optional
from urllib.parse import parse_qs, urlencode, urlparse

from luducat.plugins.sdk.json import json

logger = logging.getLogger(__name__)

_AUTH_HOST = "https://api.amazon.com"
_REGISTER_URL = f"{_AUTH_HOST}/auth/register"
_TOKEN_URL = f"{_AUTH_HOST}/auth/token"
_DEREGISTER_URL = f"{_AUTH_HOST}/auth/deregister"

# Sign-in host without "www." — the www host rejects the device sign-in
# flow parameters (verified live 2026-07-10).
_SIGNIN_URL = "https://amazon.com/ap/signin"

# US marketplace id — Amazon uses it for ALL accounts in this flow,
# including European ones (verified live with an EU account).
_MARKETPLACE_ID = "ATVPDKIKX0DER"

# Device type of the Amazon Games launcher for Windows
_DEVICE_TYPE = "A2UMVHOX7UP4V7"

_APP_NAME = "AGSLauncher for Windows"
_APP_VERSION = "1.0.0"

_CODE_PARAM = "openid.oa2.authorization_code"

_KEYRING_KEY = "session"

# Refresh this long before actual token expiry
_EXPIRY_BUFFER = 300


class AmazonSession:
    """Device-auth session manager for Amazon Games.

    Args:
        get_credential: Callback to read from keyring (key -> value|None)
        set_credential: Callback to write to keyring (key, value)
        delete_credential: Callback to delete from keyring (key)
        http_client: PluginHttpClient for HTTP requests
    """

    def __init__(
        self,
        get_credential: Callable[[str], Optional[str]],
        set_credential: Callable[[str, str], None],
        delete_credential: Callable[[str], None],
        http_client: Any,
    ):
        self._get_credential = get_credential
        self._set_credential = set_credential
        self._delete_credential = delete_credential
        self._http = http_client

        # Identity generated by build_signin_url(), consumed by
        # register_device(). Held in memory only — it is worthless
        # without the matching single-use authorization code.
        self._pending_identity: Optional[Dict[str, str]] = None

        # In-memory session cache (loaded from keyring on first access)
        self._session: Optional[Dict[str, Any]] = None
        self._session_loaded = False

    # ── Properties ──────────────────────────────────────────────────────

    @property
    def has_session(self) -> bool:
        """Whether a device registration exists (may be expired)."""
        session = self._load_session()
        return session is not None and bool(session.get("access_token"))

    @property
    def access_token(self) -> Optional[str]:
        session = self._load_session()
        return session.get("access_token") if session else None

    @property
    def user_id(self) -> Optional[str]:
        """Stable Amazon account id (amzn1.account.*)."""
        session = self._load_session()
        return session.get("user_id") if session else None

    @property
    def given_name(self) -> Optional[str]:
        session = self._load_session()
        return session.get("given_name") if session else None

    @property
    def device_serial(self) -> Optional[str]:
        """Server-confirmed device serial (basis for hardwareHash)."""
        session = self._load_session()
        return session.get("device_serial") if session else None

    # ── Sign-in flow ────────────────────────────────────────────────────

    def build_signin_url(self) -> str:
        """Generate a fresh device identity and return the sign-in URL.

        Each call replaces the pending identity — the PKCE verifier is
        bound to the challenge embedded in the returned URL.
        """
        verifier = (
            base64.urlsafe_b64encode(secrets.token_bytes(32)).rstrip(b"=")
        )
        challenge = (
            base64.urlsafe_b64encode(hashlib.sha256(verifier).digest())
            .rstrip(b"=")
        )
        # 32 uppercase hex chars, same shape the launcher generates.
        # uuid4 (not uuid1) so no MAC address or timestamp leaks into
        # the serial Amazon stores server-side.
        serial = uuid.uuid4().hex.upper()
        client_id = f"{serial}#{_DEVICE_TYPE}".encode("ascii").hex()

        self._pending_identity = {
            "code_verifier": verifier.decode(),
            "serial": serial,
            "client_id": client_id,
        }

        params = {
            "openid.ns": "http://specs.openid.net/auth/2.0",
            "openid.claimed_id": (
                "http://specs.openid.net/auth/2.0/identifier_select"
            ),
            "openid.identity": (
                "http://specs.openid.net/auth/2.0/identifier_select"
            ),
            "openid.mode": "checkid_setup",
            "openid.oa2.scope": "device_auth_access",
            "openid.ns.oa2": "http://www.amazon.com/ap/ext/oauth/2",
            "openid.oa2.response_type": "code",
            "openid.oa2.code_challenge_method": "S256",
            "openid.oa2.client_id": f"device:{client_id}",
            "language": "en_US",
            "marketPlaceId": _MARKETPLACE_ID,
            "openid.return_to": "https://www.amazon.com",
            "openid.pape.max_auth_age": "0",
            "openid.assoc_handle": "amzn_sonic_games_launcher",
            "pageId": "amzn_sonic_games_launcher",
            "openid.oa2.code_challenge": challenge.decode(),
        }
        return _SIGNIN_URL + "?" + urlencode(params)

    @staticmethod
    def extract_authorization_code(redirect_url: str) -> str:
        """Pull the single-use authorization code from a pasted redirect URL.

        Args:
            redirect_url: The full URL the browser landed on after sign-in

        Returns:
            The authorization code

        Raises:
            ValueError: If the URL carries no authorization code (stale,
                foreign, or truncated paste)
        """
        if not redirect_url or not redirect_url.strip():
            raise ValueError("No URL provided")

        query = urlparse(redirect_url.strip()).query
        code = parse_qs(query).get(_CODE_PARAM, [None])[0]
        if not code:
            raise ValueError(
                "The pasted URL carries no Amazon authorization code. "
                "Copy the FULL address the browser shows right after "
                "completing the sign-in (the code is single-use — if the "
                "page navigated on, restart the sign-in)."
            )
        return code

    def register_device(self, authorization_code: str) -> Dict[str, Any]:
        """Register this install as a device, completing the auth flow.

        Args:
            authorization_code: Code extracted from the sign-in redirect

        Returns:
            Session dict (tokens + identity)

        Raises:
            RuntimeError: If no sign-in was started or registration fails
        """
        if not self._pending_identity:
            raise RuntimeError(
                "No pending sign-in — call build_signin_url() first"
            )
        identity = self._pending_identity

        body = {
            "auth_data": {
                "authorization_code": authorization_code,
                "client_domain": "DeviceLegacy",
                "client_id": identity["client_id"],
                "code_algorithm": "SHA-256",
                "code_verifier": identity["code_verifier"],
                "use_global_authentication": False,
            },
            "registration_data": {
                "app_name": _APP_NAME,
                "app_version": _APP_VERSION,
                "device_model": "Windows",
                "device_name": None,
                "device_serial": identity["serial"],
                "device_type": _DEVICE_TYPE,
                "domain": "Device",
                "os_version": "10.0.19044.0",
            },
            "requested_extensions": ["customer_info", "device_info"],
            "requested_token_type": ["bearer", "mac_dms"],
            "user_context_map": {},
        }

        logger.info("Registering Amazon Games device")
        response = self._http.post(_REGISTER_URL, json=body, timeout=30)
        if response.status_code != 200:
            raise RuntimeError(
                f"Amazon device registration failed: "
                f"{self._parse_error(response)}"
            )

        data = response.json()
        success = data.get("response", {}).get("success", {})
        bearer = success.get("tokens", {}).get("bearer", {})
        extensions = success.get("extensions", {})
        customer = extensions.get("customer_info", {})
        device = extensions.get("device_info", {})

        access_token = bearer.get("access_token")
        refresh_token = bearer.get("refresh_token")
        if not access_token or not refresh_token:
            raise RuntimeError(
                "Amazon device registration returned no tokens"
            )

        session = {
            "access_token": access_token,
            "refresh_token": refresh_token,
            "expires_at": time.time() + self._expires_in(bearer),
            "user_id": customer.get("user_id"),
            "given_name": customer.get("given_name"),
            "device_serial": device.get("device_serial_number"),
            "serial": identity["serial"],
            "client_id": identity["client_id"],
        }
        self._store_session(session)
        self._pending_identity = None
        logger.info(
            "Amazon device registered for %s",
            session.get("given_name") or "unknown",
        )
        return session

    # ── Token lifecycle ─────────────────────────────────────────────────

    def ensure_valid(self) -> str:
        """Return a valid access token, refreshing if near expiry.

        Raises:
            RuntimeError: If not authenticated or refresh fails
        """
        session = self._load_session()
        if not session or not session.get("access_token"):
            raise RuntimeError("Not authenticated — no Amazon session")

        if time.time() >= session.get("expires_at", 0) - _EXPIRY_BUFFER:
            logger.debug("Amazon access token near expiry, refreshing")
            self.refresh()
            session = self._load_session()

        return session["access_token"]

    def refresh(self) -> Dict[str, Any]:
        """Refresh the access token using the stored refresh token.

        Only definitive auth rejections (4xx) clear the session — a
        transient server or network failure must not cost the user the
        device registration (re-registering needs the full
        password/OTP/approval dance).

        Raises:
            RuntimeError: If no session exists or the refresh fails
        """
        session = self._load_session()
        refresh_token = session.get("refresh_token") if session else None
        if not refresh_token:
            raise RuntimeError("No Amazon refresh token available")

        body = {
            "source_token": refresh_token,
            "source_token_type": "refresh_token",
            "requested_token_type": "access_token",
            "app_name": _APP_NAME,
            "app_version": _APP_VERSION,
        }
        response = self._http.post(_TOKEN_URL, json=body, timeout=30)

        if response.status_code != 200:
            error_msg = self._parse_error(response)
            if 400 <= response.status_code < 500:
                logger.warning(
                    "Amazon token refresh rejected (%s), clearing session",
                    error_msg,
                )
                self.clear()
            else:
                logger.warning(
                    "Amazon token refresh failed transiently: %s", error_msg
                )
            raise RuntimeError(f"Amazon token refresh failed: {error_msg}")

        data = response.json()
        access_token = data.get("access_token")
        if not access_token:
            raise RuntimeError("Amazon token refresh returned no token")

        session["access_token"] = access_token
        session["expires_at"] = time.time() + self._expires_in(data)
        self._store_session(session)
        logger.debug("Amazon token refreshed")
        return session

    def deregister(self) -> None:
        """Deregister the device (logout), then clear local state.

        Local state is cleared even if the HTTP call fails — the user
        asked to log out; a dangling server-side registration expires
        on its own.
        """
        session = self._load_session()
        if not session or not session.get("access_token"):
            self.clear()
            return

        try:
            self._http.post(
                _DEREGISTER_URL,
                json={
                    "request_metadata": {
                        "app_name": _APP_NAME,
                        "app_version": _APP_VERSION,
                    }
                },
                headers={
                    "Authorization": f"bearer {session['access_token']}"
                },
                timeout=10,
            )
            logger.info("Amazon device deregistered")
        except Exception as e:
            logger.warning("Failed to deregister Amazon device: %s", e)

        self.clear()

    def clear(self) -> None:
        """Delete session from keyring and clear in-memory state."""
        try:
            self._delete_credential(_KEYRING_KEY)
        except Exception:
            pass
        self._session = None
        self._session_loaded = False
        logger.debug("Amazon session cleared")

    # ── Private helpers ─────────────────────────────────────────────────

    @staticmethod
    def _expires_in(token_data: Dict[str, Any]) -> int:
        """Token lifetime in seconds; the API sends it as a string."""
        try:
            return int(token_data.get("expires_in", 3600))
        except (TypeError, ValueError):
            return 3600

    def _load_session(self) -> Optional[Dict[str, Any]]:
        """Load session from keyring (cached in memory after first load)."""
        if self._session_loaded:
            return self._session

        raw = self._get_credential(_KEYRING_KEY)
        if raw:
            try:
                self._session = json.loads(raw)
            except (json.JSONDecodeError, ValueError):
                logger.warning("Corrupt Amazon session in keyring, clearing")
                self._session = None
                try:
                    self._delete_credential(_KEYRING_KEY)
                except Exception:
                    pass
        else:
            self._session = None

        self._session_loaded = True
        return self._session

    def _store_session(self, session: Dict[str, Any]) -> None:
        self._set_credential(_KEYRING_KEY, json.dumps(session))
        self._session = session
        self._session_loaded = True

    @staticmethod
    def _parse_error(response) -> str:
        """Extract a human-readable message from an error response."""
        try:
            data = response.json()
            error = data.get("response", {}).get("error", {})
            msg = error.get("message") or data.get("error_description") \
                or data.get("error") or data.get("message")
            if msg:
                return f"{msg} (HTTP {response.status_code})"
        except Exception:
            pass
        return f"HTTP {response.status_code}"
