# This file is part of luducat. License: GPL-3.0-or-later. Contact: luducat@trinity2k.net
# store.py

"""GOG Store Plugin Implementation

Provides GOG.com game library integration via:
- GOG API (getFilteredProducts + products API) for owned games and metadata
- GOGdb database import for supplementary catalog data (developers, genres, etc.)
- Galaxy 2.0 DB for playtime and installation status (Windows)
"""

import logging
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple, TYPE_CHECKING

from luducat.plugins.sdk.constants import USER_AGENT
from luducat.plugins.sdk.datetime import utc_now
from luducat.plugins.base import Game, PluginError, StorePlugin
from .database import GogDatabase, GogGame
from .gogdb_importer import GogdbImporter
from .galaxy_db import (
    get_playtime_data as _galaxy_get_playtime,
    get_installed_games_batch as _galaxy_get_installed,
)

if TYPE_CHECKING:
    from .gog_api import GogApiClient

logger = logging.getLogger(__name__)

# Days after which GOGdb import is considered stale
IMPORT_FRESHNESS_DAYS = 30


def _fix_gog_cdn_url(url: Optional[str]) -> Optional[str]:
    """Ensure GOG CDN URLs have a file extension.

    The owned-games API returns image hashes without extensions but the CDN
    requires one (returns 404 otherwise).  GOGdb import and newer code paths
    already append ``.jpg``; this catches legacy DB rows and any remaining
    code paths that don't.
    """
    if url and "gog-statics.com/" in url and not url.endswith(('.jpg', '.png', '.webp')):
        return url + ".jpg"
    return url


# Regex matching numbered-CDN product image URLs: images-N.gog-statics.com/HASH.jpg
# These are horizontal banners (1600x740) from getFilteredProducts.
# GOGdb boxart uses the non-numbered images.gog-statics.com and is already vertical.
import re
_NUMBERED_CDN_RE = re.compile(
    r'^(https?://images-\d+\.gog-statics\.com/[a-f0-9]+)\.jpg$'
)


def _is_horizontal_gog_url(url: Optional[str]) -> bool:
    """Detect numbered-CDN URLs which are always horizontal product banners."""
    if not url:
        return False
    return bool(_NUMBERED_CDN_RE.match(url))


def _force_vertical_cover(url: Optional[str]) -> Optional[str]:
    """Rewrite horizontal GOG product images to vertical covers.

    The getFilteredProducts API ``image`` field yields a horizontal 1600x740
    banner.  The same hash with ``_glx_vertical_cover`` suffix returns a proper
    342x482 vertical cover generated by the GOG CDN.

    Only rewrites numbered-CDN URLs (``images-N.gog-statics.com``) which come
    from the owned-games API.  GOGdb boxart URLs (``images.gog-statics.com``)
    are already vertical and left untouched.
    """
    if not url:
        return url
    m = _NUMBERED_CDN_RE.match(url)
    if m:
        return m.group(1) + "_glx_vertical_cover.webp"
    return url



class GogdbImportRequired(PluginError):
    """Raised when GOGdb import is required before sync can proceed"""
    pass


class GogdbImportRecommended(PluginError):
    """Raised when GOGdb import is recommended (first authenticated sync).

    Unlike GogdbImportRequired, sync can proceed without GOGdb data
    but results will be lower quality (horizontal covers, missing metadata).
    """
    pass


class GogStore(StorePlugin):
    """GOG Store Plugin

    Integrates with GOG.com game library using:
    - GOGdb database import for game catalog
    - GOG API for owned games and metadata enrichment
    - Galaxy 2.0 DB for playtime and installation data (Windows)

    Authentication is optional - GOGdb provides catalog data without auth.
    Game launching is handled by bridge plugins via RuntimeManager.
    """

    # GOG cookie configuration
    COOKIE_DOMAIN = ".gog.com"
    REQUIRED_COOKIE = "gog-al"

    def __init__(self, config_dir: Path, cache_dir: Path, data_dir: Path):
        super().__init__(config_dir, cache_dir, data_dir)
        self._db: Optional[GogDatabase] = None
        self._api_client: Optional["GogApiClient"] = None
        self._browser_cookies_checked = False
        self._title_index: Optional[Dict[str, int]] = None

    @property
    def store_name(self) -> str:
        return "gog"

    @property
    def display_name(self) -> str:
        return "GOG"

    def _get_db(self) -> GogDatabase:
        """Get or create database connection"""
        if self._db is None:
            self._db = GogDatabase(self.get_database_path())
            self._db.initialize()
        return self._db

    def _get_api_client(self) -> "GogApiClient":
        """Get or create GOG API client"""
        if self._api_client is None:
            from .gog_api import GogApiClient
            self._api_client = GogApiClient(self, http_client=self.http)
        return self._api_client

    def _has_valid_cookies(self) -> bool:
        """Check if we have stored authentication cookies"""
        return bool(self.get_credential("gog_al"))

    def _check_browser_cookies(self) -> bool:
        """Check browser for GOG login cookies and import if found

        This is called automatically when checking auth status.
        If cookies are found in the browser, they are imported.

        Returns:
            True if valid cookies were found and imported
        """
        if self._browser_cookies_checked:
            return self._has_valid_cookies()

        self._browser_cookies_checked = True

        # Don't check if we already have cookies
        if self._has_valid_cookies():
            return True

        # Check if credential manager is available
        if not self._credential_manager:
            logger.debug("Credential manager not initialized, skipping browser cookie check")
            return False

        try:
            from luducat.plugins.sdk.cookies import get_browser_cookie_manager

            manager = get_browser_cookie_manager()
            cookies, browser = manager.get_cookies_for_domain(
                self.COOKIE_DOMAIN, self.REQUIRED_COOKIE
            )
            if cookies:
                logger.info(f"Found GOG login in {browser or 'browser'}, importing cookies")
                self.handle_cookies(cookies)
                return True
        except Exception as e:
            logger.debug(f"Could not check browser cookies: {e}")

        return False

    def refresh_auth_state(self) -> bool:
        """Refresh authentication state by checking browser cookies

        Call this to re-check browser for cookies (e.g., after user logs in).

        Returns:
            True if authenticated
        """
        self._browser_cookies_checked = False
        return self._check_browser_cookies()

    def get_database_path(self) -> Path:
        """Return path to plugin's catalog database"""
        return self.data_dir / "catalog.db"

    def is_available(self) -> bool:
        """Check if GOG plugin is usable.

        Always returns True — GOGdb import and GOG API are always available.
        Game launching is handled by bridge plugins via RuntimeManager.
        """
        return True

    async def authenticate(self) -> bool:
        """Perform authentication flow

        Authentication is optional - GOGdb works without authentication.
        When authenticated, enables fetching owned games list.

        Returns:
            True if already authenticated with valid cookies.
            False if login dialog is required.
        """
        # Check if we have cookies
        if self._has_valid_cookies():
            # Optionally verify they're still valid
            api = self._get_api_client()
            if await api.verify_login():
                return True
            logger.warning("GOG cookies expired or invalid")

        # No valid cookies - need login
        return False

    def is_authenticated(self) -> bool:
        """Check if authenticated with stored cookies

        On first call, checks browser for existing login and imports
        cookies automatically if found.

        Returns:
            True if we have authentication cookies.
            Note: GOGdb import works without authentication.
        """
        # Check browser cookies on first call (auto-import if found)
        self._check_browser_cookies()
        return self._has_valid_cookies()

    def get_account_identifier(self) -> Optional[str]:
        """Return the GOG auth cookie identifying the current account."""
        return self.get_credential("gog_al")

    def get_auth_status(self) -> tuple:
        """Get authentication status with details

        Returns:
            Tuple of (is_authenticated: bool, status_message: str)
        """
        # Check browser for cookies first
        self._check_browser_cookies()

        if self._has_valid_cookies():
            # Check which browser has the cookies
            try:
                from luducat.plugins.sdk.dialogs import get_login_status
                _logged_in, browser = get_login_status(self.COOKIE_DOMAIN, self.REQUIRED_COOKIE)
                if browser:
                    return True, _("Connected ({browser})").format(browser=browser)
            except Exception:
                pass

            return True, _("Connected")
        else:
            return False, _("Not connected")

    def get_login_config(self):
        """Get browser login configuration for login dialog

        Returns:
            BrowserLoginConfig for GOG authentication
        """
        BrowserLoginConfig = None
        try:
            from luducat.plugins.sdk.dialogs import get_browser_login_config_class
            BrowserLoginConfig = get_browser_login_config_class()
        except ImportError:
            pass
        if BrowserLoginConfig is None:
            return None
        return BrowserLoginConfig(
            name=self.display_name,
            login_url="https://www.gog.com/account",
            cookie_domain=self.COOKIE_DOMAIN,
            required_cookie=self.REQUIRED_COOKIE,
            additional_cookies=["gog_lc"],
        )

    # Backwards compatibility
    def get_oauth_config(self):
        """Deprecated: Use get_login_config() instead"""
        return self.get_login_config()

    async def handle_oauth_code(self, auth_code: str, redirect_uri: str = None) -> bool:
        """Handle login from cookie dialog

        The auth_code parameter now contains the gog-al cookie value,
        and redirect_uri contains the full cookies dict.

        Args:
            auth_code: The gog-al cookie value (for compatibility)
            redirect_uri: Unused (kept for compatibility)

        Returns:
            True if login successful
        """
        # This is now called with cookies from the dialog
        # The dialog's get_cookies() returns the full dict
        # For now, just store the main auth cookie
        if auth_code:
            self.set_credential("gog_al", auth_code)
            logger.info("GOG login successful (cookies stored)")
            return True
        return False

    def handle_cookies(self, cookies: Dict[str, str]) -> bool:
        """Store authentication cookies from browser

        Args:
            cookies: Dict of cookie name -> value

        Returns:
            True if cookies were stored
        """
        api = self._get_api_client()
        api.store_cookies(cookies)
        return True

    def logout(self) -> None:
        """Clear stored authentication cookies (logout)"""
        api = self._get_api_client()
        api.clear_cookies()
        logger.info("Logged out of GOG")

    async def fetch_user_games(
        self,
        status_callback: Optional[Any] = None,
        cancel_check: Optional[Callable[[], bool]] = None,
    ) -> List[str]:
        """Fetch list of user's owned game IDs from GOG API.

        Also harvests basic metadata from getFilteredProducts response
        and upserts it to catalog.db, ensuring every owned game has at
        least title + cover + platforms even without GOGdb.

        Args:
            status_callback: Optional callback(message) for progress updates
            cancel_check: Optional callback returning True if cancelled

        Returns:
            List of GOG IDs the user owns (empty if not authenticated)
        """
        if not self.is_authenticated():
            logger.info("GOG: Not authenticated, cannot fetch owned games")
            return []

        from datetime import datetime
        from luducat.plugins.sdk.config import get_config_value

        # Log last scan age for debugging
        try:
            last_scanned = get_config_value("gog.gogdb_last_scanned")
            if last_scanned:
                age = datetime.now() - datetime.fromisoformat(last_scanned)
                logger.debug(f"Last GOG data scan: {last_scanned} ({age.days} days ago)")
            else:
                logger.debug("No previous GOG data scan recorded")
        except Exception:
            pass

        logger.info("Fetching owned games from GOG API")
        try:
            api = self._get_api_client()
            owned_ids, product_dicts = await api.get_owned_games(
                status_callback=status_callback,
                cancel_check=cancel_check,
            )
            logger.info(f"Found {len(owned_ids)} owned GOG games")

            # Harvest basic metadata from getFilteredProducts response
            if product_dicts:
                self._upsert_basic_metadata(product_dicts)

            # Update last-scanned timestamp
            try:
                from luducat.plugins.sdk.config import set_config_value
                set_config_value("gog.gogdb_last_scanned", datetime.now().isoformat())
            except Exception:
                pass

            app_ids = [str(gogid) for gogid in owned_ids]

            # Detect delisted games: owned but no longer in GOG catalog
            # Round 1: catalog delta (owned - catalog = candidates)
            # Round 2: bundle resolution (filter out re-packaged games)
            self._delisted_app_ids = set()
            if self.get_setting("detect_delisted_games"):
                try:
                    api = self._get_api_client()
                    catalog = await api.fetch_full_catalog(
                        status_callback=status_callback,
                        cancel_check=cancel_check,
                    )
                    if not catalog:
                        logger.warning("Empty catalog — skipping delisted detection")
                    else:
                        catalog_id_strs = {str(gid) for gid in catalog}
                        candidates = set(app_ids) - catalog_id_strs

                        if candidates:
                            # Round 2: check bundle availability
                            db = self._get_db()
                            resolved = set()
                            for cid in candidates:
                                bundle_ids = db.get_bundle_ids(int(cid))
                                if not bundle_ids:
                                    continue  # no bundle → stays as candidate
                                for bid in bundle_ids:
                                    if str(bid) in catalog_id_strs:
                                        resolved.add(cid)
                                        # Also resolve siblings in same bundle
                                        for sib in db.get_games_in_bundle(bid):
                                            s = str(sib)
                                            if s in candidates:
                                                resolved.add(s)
                                        break
                            candidates -= resolved
                            if resolved:
                                logger.info(
                                    "Bundle resolution: %d games in active bundles, "
                                    "removed from delisted candidates",
                                    len(resolved),
                                )

                        self._delisted_app_ids = candidates
                        logger.info(
                            "GOG delisted: %d confirmed (owned: %d, catalog: %d)",
                            len(candidates), len(app_ids), len(catalog),
                        )
                except Exception as e:
                    logger.warning("Delisted detection failed: %s", e)

            return app_ids
        except Exception as e:
            logger.error(f"Failed to fetch owned games: {e}")
            raise PluginError(f"Failed to fetch owned games: {e}") from e

    def _upsert_basic_metadata(self, product_dicts: List[Dict[str, Any]]) -> None:
        """Upsert basic metadata from getFilteredProducts into catalog.db.

        This ensures every owned game has at least title, cover, platforms,
        category, rating, and user tags — even without GOGdb import.
        """
        from .database import GogGame
        db = self._get_db()
        count = 0

        for product in product_dicts:
            gogid = product.get("id")
            if not gogid:
                continue

            # Only games, skip movies
            if not product.get("isGame", True):
                continue

            existing = db.get_game(gogid)
            if existing:
                # Update user tags and rating (these only come from API)
                tags = product.get("tags")
                if tags:
                    existing.user_tags = tags
                rating = product.get("rating")
                if rating is not None:
                    existing.rating = rating
                # Update category as genre if no genres set
                category = product.get("category")
                if category and not existing.genres:
                    existing.genres = [category]
            else:
                # Create new record with basic metadata
                image_url = product.get("image")
                if image_url and image_url.startswith("//"):
                    image_url = "https:" + image_url
                image_url = _force_vertical_cover(_fix_gog_cdn_url(image_url))

                works_on = product.get("worksOn", {})
                release_date_raw = product.get("releaseDate")
                release_date = None
                if isinstance(release_date_raw, dict):
                    release_date = release_date_raw.get("date", "")[:10]
                elif isinstance(release_date_raw, str):
                    release_date = release_date_raw[:10]

                game = GogGame(
                    gogid=gogid,
                    title=product.get("title", "Unknown"),
                    slug=product.get("slug", ""),
                    type="game",
                    cover_url=image_url,
                    windows=works_on.get("Windows", False),
                    mac=works_on.get("Mac", False),
                    linux=works_on.get("Linux", False),
                    release_date=release_date,
                    is_free=product.get("price", 0) == 0,
                    data_source="gog_api_basic",
                    gogdb_imported=False,
                    enriched=False,
                )
                # Set JSON fields
                category = product.get("category")
                if category:
                    game.genres = [category]
                tags = product.get("tags")
                if tags:
                    game.user_tags = tags
                rating = product.get("rating")
                if rating is not None:
                    game.rating = rating

                db.session.add(game)
                count += 1

        try:
            db.commit()
        except Exception as e:
            logger.warning(f"Failed to commit basic metadata upsert: {e}")
            db.rollback()
        if count:
            logger.info(f"Upserted {count} new games from getFilteredProducts")

    async def _enrich_gap_games(
        self,
        owned_ids: List[int],
        status_callback: Optional[Any] = None,
        cancel_check: Optional[Callable[[], bool]] = None,
    ) -> Dict[str, int]:
        """Enrich owned games that have no GOGdb or catalog data (3-tier strategy).

        Tier 2: Fetch individual product.json from GOGdb.org
        Tier 3: If GOGdb 404, fetch from catalog API

        Only runs for games where gogdb_imported=False AND catalog_enriched=False.

        Args:
            owned_ids: List of owned GOG IDs
            status_callback: Optional progress callback(message, current, total)
            cancel_check: Optional cancel check callback

        Returns:
            Stats dict with enriched/errors counts
        """
        db = self._get_db()
        gap_ids = db.get_gap_games(owned_ids)

        if not gap_ids:
            return {"gap_enriched": 0, "gap_errors": 0}

        total = len(gap_ids)
        logger.info(f"Gap-filling {total} games without GOGdb/catalog data")

        if status_callback:
            status_callback(f"Enriching {total} games...", 0, total)

        importer = GogdbImporter(self.data_dir, self.cache_dir, http_client=self.http)
        api = self._get_api_client()
        enriched = 0
        errors = 0

        for idx, gogid in enumerate(gap_ids, 1):
            if cancel_check and cancel_check():
                logger.info(f"Gap-fill cancelled at {idx}/{total}")
                break

            game = db.get_game(gogid)
            if not game:
                continue

            if status_callback:
                status_callback(game.title, idx, total)

            try:
                # Tier 2: Try individual GOGdb fetch
                gogdb_game = importer.fetch_product_from_api(gogid)
                if gogdb_game:
                    # Apply GOGdb data to existing record
                    self._apply_gogdb_data(game, gogdb_game)
                    game.gogdb_imported = True
                    db.commit()
                    enriched += 1
                    logger.debug(f"Gap-filled {gogid} ({game.title}) via GOGdb")
                    continue

                # Tier 3: Catalog API fallback
                catalog_data = await api.fetch_catalog_for_game(gogid, game.title)
                if catalog_data:
                    self._apply_catalog_data(game, catalog_data)
                    game.catalog_enriched = True
                    db.commit()
                    enriched += 1
                    logger.debug(f"Gap-filled {gogid} ({game.title}) via catalog API")
                    continue

                # Neither source had data — mark as attempted so we don't retry
                game.catalog_enriched = True
                db.commit()
                logger.debug(f"No gap-fill data for {gogid} ({game.title})")

            except Exception as e:
                logger.warning(f"Failed to gap-fill {gogid}: {e}")
                db.rollback()
                errors += 1

        if enriched:
            logger.info(f"Gap-fill complete: {enriched}/{total} enriched, {errors} errors")

        return {"gap_enriched": enriched, "gap_errors": errors}

    async def _enrich_bulk_catalog(
        self,
        status_callback: Optional[Any] = None,
        cancel_check: Optional[Callable[[], bool]] = None,
    ) -> Dict[str, int]:
        """Bulk-enrich ALL owned games from the GOG catalog API.

        Two-phase:
        1. Fetch entire catalog via paginated API
        2. Apply catalog data to owned games where catalog_enriched=False

        Batch-commits every 100 games for safety.

        Args:
            status_callback: Optional callback(message, current, total)
            cancel_check: Optional cancel check callback

        Returns:
            Stats dict with catalog_fetched, enriched, errors counts
        """
        api = self._get_api_client()
        db = self._get_db()

        # Phase 1: Fetch full catalog
        catalog = await api.fetch_full_catalog(
            status_callback=status_callback,
            cancel_check=cancel_check,
        )

        if cancel_check and cancel_check():
            return {"catalog_fetched": len(catalog), "enriched": 0, "errors": 0}

        if not catalog:
            logger.warning("Catalog scan returned no products")
            return {"catalog_fetched": 0, "enriched": 0, "errors": 0}

        # Phase 2: Apply to owned games
        owned_ids = db.get_all_gogids(include_dlc=False)
        unenriched = db.get_catalog_unenriched_gogids(owned_ids)

        if not unenriched:
            # Even if all owned games are enriched, apply to any owned game
            # that has a catalog entry (for authoritative overwrite)
            unenriched = [gid for gid in owned_ids if gid in catalog]

        total = len(unenriched)
        if not total:
            logger.info("No owned games to enrich from catalog")
            return {"catalog_fetched": len(catalog), "enriched": 0, "errors": 0}

        if status_callback:
            status_callback(f"Applying catalog data to {total} games...", 0, total)

        enriched = 0
        errors = 0

        for idx, gogid in enumerate(unenriched, 1):
            if cancel_check and cancel_check():
                logger.info(f"Catalog enrichment cancelled at {idx}/{total}")
                break

            catalog_data = catalog.get(gogid)
            if not catalog_data:
                continue

            try:
                game = db.get_game(gogid)
                if game:
                    self._apply_catalog_data(game, catalog_data)
                    enriched += 1

                    if status_callback and idx % 50 == 0:
                        status_callback(
                            f"Applying catalog data... ({idx}/{total})",
                            idx,
                            total,
                        )

                    # Batch commit every 100 games
                    if enriched % 100 == 0:
                        db.commit()
            except Exception as e:
                logger.warning(f"Failed to apply catalog data for {gogid}: {e}")
                db.rollback()
                errors += 1

        # Final commit
        try:
            db.commit()
        except Exception as e:
            logger.warning(f"Final catalog commit failed: {e}")
            db.rollback()

        if status_callback:
            status_callback(f"Catalog enrichment complete: {enriched} games", total, total)

        logger.info(
            f"Bulk catalog enrichment: {enriched}/{total} enriched, "
            f"{errors} errors, {len(catalog)} catalog products"
        )

        return {
            "catalog_fetched": len(catalog),
            "enriched": enriched,
            "errors": errors,
        }

    async def prepare_metadata(self, status_callback=None, cancel_check=None):
        """Bulk catalog scan for vertical covers and enrichment.

        Runs after skeletons are created. Full scan (~140 pages) on first
        sync or when freshness timer expires; incremental otherwise.
        """
        CATALOG_FRESHNESS_DAYS = 21

        # Check freshness timer
        from luducat.plugins.sdk.config import get_config_value, set_config_value
        from datetime import datetime, timedelta

        last_scan = get_config_value("gog.catalog_last_scanned")
        needs_refresh = True
        if last_scan:
            try:
                age = datetime.now() - datetime.fromisoformat(last_scan)
                needs_refresh = age > timedelta(days=CATALOG_FRESHNESS_DAYS)
            except (ValueError, TypeError):
                pass

        if not needs_refresh:
            # Between full scans, new purchases are enriched per-game
            # in fetch_game_metadata() via the catalog API fallback.
            return

        await self._enrich_bulk_catalog(
            status_callback=status_callback,
            cancel_check=cancel_check,
        )

        # Only update timestamp if not cancelled
        if not (cancel_check and cancel_check()):
            set_config_value(
                "gog.catalog_last_scanned", datetime.now().isoformat()
            )

    def _apply_gogdb_data(self, existing: GogGame, gogdb_game: GogGame) -> None:
        """Apply GOGdb product data to an existing basic metadata record.

        Only overwrites fields that are currently empty/default.
        """
        # GOGdb boxart is a dedicated vertical asset (separately uploaded,
        # not a CDN crop) — always preferred over the horizontal banner hash
        # from getFilteredProducts.
        if gogdb_game.cover_url:
            existing.cover_url = gogdb_game.cover_url
        if not existing.background_url and gogdb_game.background_url:
            existing.background_url = gogdb_game.background_url
        if not existing.galaxy_background_url and gogdb_game.galaxy_background_url:
            existing.galaxy_background_url = gogdb_game.galaxy_background_url
        if not existing.logo_url and gogdb_game.logo_url:
            existing.logo_url = gogdb_game.logo_url
        if not existing.icon_url and gogdb_game.icon_url:
            existing.icon_url = gogdb_game.icon_url
        if not existing.icon_square_url and gogdb_game.icon_square_url:
            existing.icon_square_url = gogdb_game.icon_square_url
        if not existing.description and gogdb_game.description:
            existing.description = gogdb_game.description
        if not existing.short_description and gogdb_game.short_description:
            existing.short_description = gogdb_game.short_description
        if not existing.developers:
            existing.developers = gogdb_game.developers
        if not existing.publishers:
            existing.publishers = gogdb_game.publishers
        if not existing.genres:
            existing.genres = gogdb_game.genres
        if not existing.tags:
            existing.tags = gogdb_game.tags
        if not existing.features:
            existing.features = gogdb_game.features
        if not existing.screenshots:
            existing.screenshots = gogdb_game.screenshots
        # Always update these from GOGdb (richer data)
        if gogdb_game.series_name:
            existing.series_name = gogdb_game.series_name
            existing.series_id = gogdb_game.series_id
        if gogdb_game.age_rating is not None:
            existing.age_rating = gogdb_game.age_rating
        if gogdb_game.localizations:
            existing.localizations = gogdb_game.localizations
        if gogdb_game.editions:
            existing.editions = gogdb_game.editions
        if gogdb_game.includes_games:
            existing.includes_games = gogdb_game.includes_games
        if gogdb_game.is_included_in:
            existing.is_included_in = gogdb_game.is_included_in
        if gogdb_game.copyright_notice:
            existing.copyright_notice = gogdb_game.copyright_notice
        if gogdb_game.is_using_dosbox is not None:
            existing.is_using_dosbox = gogdb_game.is_using_dosbox
        if gogdb_game.is_in_development is not None:
            existing.is_in_development = gogdb_game.is_in_development
        if gogdb_game.store_release_date:
            existing.store_release_date = gogdb_game.store_release_date
        if gogdb_game.global_release_date:
            existing.global_release_date = gogdb_game.global_release_date
        if gogdb_game.store_link:
            existing.store_link = gogdb_game.store_link
        if gogdb_game.forum_link:
            existing.forum_link = gogdb_game.forum_link
        if gogdb_game.support_link:
            existing.support_link = gogdb_game.support_link
        if gogdb_game.rank_bestselling is not None:
            existing.rank_bestselling = gogdb_game.rank_bestselling
        if gogdb_game.rank_trending is not None:
            existing.rank_trending = gogdb_game.rank_trending
        if not existing.release_date and gogdb_game.release_date:
            existing.release_date = gogdb_game.release_date
        existing.data_source = "gogdb"
        existing.last_updated = utc_now()

    def _apply_catalog_data(
        self, existing: GogGame, catalog: Dict[str, Any]
    ) -> None:
        """Apply catalog API data to an existing game record.

        Catalog is the **authoritative source** within the GOG plugin —
        always overwrites when it has data. This ensures the freshest,
        highest-quality data from GOG's own catalog API is used.
        """
        # Images — catalog always overwrites
        if catalog.get("cover_vertical_url"):
            existing.cover_vertical_url = catalog["cover_vertical_url"]
        if catalog.get("cover_horizontal_url"):
            existing.cover_horizontal_url = catalog["cover_horizontal_url"]
        if catalog.get("logo_url"):
            existing.logo_url = catalog["logo_url"]
        if catalog.get("galaxy_background_url"):
            existing.galaxy_background_url = catalog["galaxy_background_url"]
        if catalog.get("screenshots"):
            existing.screenshots = catalog["screenshots"]

        # Metadata — catalog always overwrites
        if catalog.get("tags"):
            existing.tags = catalog["tags"]
        if catalog.get("features"):
            existing.features = catalog["features"]
        if catalog.get("genres"):
            existing.genres = catalog["genres"]
        if catalog.get("developers"):
            existing.developers = catalog["developers"]
        if catalog.get("publishers"):
            existing.publishers = catalog["publishers"]

        # Content ratings & pricing (new fields)
        if catalog.get("content_ratings"):
            existing.content_ratings = catalog["content_ratings"]
        if catalog.get("price_json"):
            existing.price_json = catalog["price_json"]
        if catalog.get("product_state"):
            existing.product_state = catalog["product_state"]

        # Ratings
        if catalog.get("reviews_rating") is not None:
            existing.rating = catalog["reviews_rating"]
        if catalog.get("reviews_count") is not None:
            existing.reviews_count = catalog["reviews_count"]

        # Links
        if catalog.get("store_link"):
            existing.store_link = catalog["store_link"]

        # Editions
        if catalog.get("editions"):
            existing.editions = catalog["editions"]

        # Dates
        if catalog.get("global_release_date"):
            rd = str(catalog["global_release_date"])
            existing.global_release_date = rd.split("T")[0] if "T" in rd else rd[:10]
        if catalog.get("release_date"):
            rd = str(catalog["release_date"])
            existing.release_date = rd.split("T")[0] if "T" in rd else rd[:10]
        if catalog.get("store_release_date"):
            rd = str(catalog["store_release_date"])
            existing.store_release_date = rd.split("T")[0] if "T" in rd else rd[:10]

        # Platform support from catalog
        os_list = catalog.get("operating_systems", [])
        if os_list:
            existing.windows = "windows" in os_list
            existing.mac = "osx" in os_list or "mac" in os_list
            existing.linux = "linux" in os_list

        # Languages from catalog
        lang_data = catalog.get("languages_data")
        if isinstance(lang_data, dict) and lang_data:
            # Build localizations-style list from userPreferredLanguage
            code = lang_data.get("code", "")
            in_audio = lang_data.get("inAudio", False)
            in_text = lang_data.get("inText", False)
            if code and not existing.localizations:
                existing.localizations = [{
                    "code": code,
                    "name": code,
                    "text": in_text,
                    "audio": in_audio,
                }]

        existing.catalog_enriched = True
        existing.data_source = "catalog"
        existing.last_updated = utc_now()

    async def fetch_game_metadata(
        self, app_ids: List[str], download_images: bool = False
    ) -> List[Game]:
        """Fetch game metadata from catalog database, with GOG products API fallback.

        Sync flow:
        1. Look up game in local catalog cache (catalog.db)
        2. If not in cache, fetch from GOG products API and cache locally
        3. Return Game objects for all found games

        Args:
            app_ids: List of GOG IDs (as strings)
            download_images: If True, download images (not implemented yet)

        Returns:
            List of Game objects
        """
        db = self._get_db()
        gogids = [int(app_id) for app_id in app_ids]

        games = []
        skipped = 0
        for gogid in gogids:
            gog_game = db.get_game(gogid)
            source = "cache"

            # If not in local cache, fetch from GOG products API
            if gog_game is None:
                logger.info(f"Game {gogid} not in cache, fetching from GOG products API")
                gog_game = await self._fetch_from_products_api(gogid)
                source = "gog_api"

            # Per-game catalog fallback for new purchases between scans
            if gog_game and not gog_game.cover_vertical_url and not gog_game.catalog_enriched:
                try:
                    api = self._get_api_client()
                    catalog_data = await api.fetch_catalog_for_game(gogid, gog_game.title)
                    if catalog_data:
                        self._apply_catalog_data(gog_game, catalog_data)
                        db.commit()
                        source = "catalog_fallback"
                except Exception as e:
                    logger.debug(f"Per-game catalog fallback failed for {gogid}: {e}")

            if gog_game:
                game = self._convert_to_plugin_game(gog_game)
                games.append(game)
                logger.debug(f"Added game {gogid} ({gog_game.title}) from {source}")
            else:
                logger.warning(f"SKIPPED: Could not find metadata for GOG game {gogid} - not adding to sync")
                skipped += 1

        logger.info(f"fetch_game_metadata: {len(games)} added, {skipped} skipped (no metadata)")
        return games

    async def _fetch_from_products_api(self, gogid: int) -> Optional[GogGame]:
        """Fetch a single game from GOG's public products API and cache it.

        Args:
            gogid: GOG product ID

        Returns:
            GogGame from local DB (after caching) or None
        """
        from .gog_api import GogApiClient
        from .database import GogGame as GogGameModel

        api = self._get_api_client()
        metadata = await api.get_product_metadata(gogid)
        if not metadata:
            return None

        db = self._get_db()

        # Create or update GogGame record
        existing = db.get_game(gogid)
        if existing:
            # Enrich existing record with products API data
            self._apply_products_api_data(existing, metadata)
        else:
            game = GogGameModel(
                gogid=gogid,
                title=metadata.get("title", "Unknown"),
                slug=metadata.get("slug", ""),
                type=metadata.get("game_type", "game"),
                description=metadata.get("description"),
                description_lead=metadata.get("description_lead"),
                description_cool=metadata.get("description_cool"),
                background_url=metadata.get("background_url"),
                logo_url=metadata.get("logo_url"),
                icon_url=metadata.get("icon_url"),
                windows=metadata.get("windows", False),
                mac=metadata.get("mac", False),
                linux=metadata.get("linux", False),
                release_date=metadata.get("release_date"),
                data_source="gog_api_full",
                gogdb_imported=False,
                enriched=True,
            )
            game.screenshots = metadata.get("screenshots", [])
            game.downloads_json = metadata.get("downloads_json", {})
            game.dlcs = metadata.get("dlcs", [])
            game.videos = metadata.get("videos", [])
            game.languages = metadata.get("languages", {})
            game.links = metadata.get("links", {})
            game.changelog = metadata.get("changelog")
            db.session.add(game)

        try:
            db.commit()
        except Exception as e:
            logger.warning(f"Failed to cache product {gogid}: {e}")
            db.rollback()
            return None
        logger.info(f"Cached product from GOG API: {gogid}")
        return db.get_game(gogid)

    def _apply_products_api_data(self, game, metadata: Dict[str, Any]) -> None:
        """Apply products API metadata to an existing GogGame record."""
        # Only overwrite if the field is currently empty/default
        if not game.description and metadata.get("description"):
            game.description = metadata["description"]
        if not game.description_lead:
            game.description_lead = metadata.get("description_lead")
        if not game.description_cool:
            game.description_cool = metadata.get("description_cool")
        if not game.background_url and metadata.get("background_url"):
            game.background_url = metadata["background_url"]
        if not game.logo_url and metadata.get("logo_url"):
            game.logo_url = metadata["logo_url"]
        if not game.icon_url and metadata.get("icon_url"):
            game.icon_url = metadata["icon_url"]
        if not game.screenshots and metadata.get("screenshots"):
            game.screenshots = metadata["screenshots"]

        # Always update rich data from products API
        game.downloads_json = metadata.get("downloads_json", {})
        game.dlcs = metadata.get("dlcs", [])
        game.videos = metadata.get("videos", [])
        game.languages = metadata.get("languages", {})
        game.links = metadata.get("links", {})
        game.changelog = metadata.get("changelog")
        game.enriched = True
        game.data_source = "gog_api_full"

    def _convert_to_plugin_game(self, gog_game: GogGame) -> Game:
        """Convert GogGame database model to plugin Game dataclass"""
        gogid = str(gog_game.gogid)

        # Store page URL as fallback hint — RuntimeManager + bridges handle actual launching
        launch_url = self.get_store_page_url(gogid)

        # Cover priority (all vertical):
        #   1. catalog coverVertical (dedicated vertical URL from catalog API)
        #   2. GOGdb image_boxart via cover_url (already vertical, non-numbered CDN)
        #   3. CDN vertical crop suffix (last resort -- forces vertical via _glx_vertical_cover.webp)
        cover = (
            gog_game.cover_vertical_url
            or _fix_gog_cdn_url(gog_game.cover_url)
        )
        if cover and _is_horizontal_gog_url(cover):
            cover = _force_vertical_cover(cover)

        # Background priority: galaxy > v0 background
        background = (
            _fix_gog_cdn_url(gog_game.galaxy_background_url)
            or _fix_gog_cdn_url(gog_game.background_url)
        )

        return Game(
            store_app_id=gogid,
            store_name=self.store_name,
            title=gog_game.title,
            launch_url=launch_url,
            short_description=gog_game.short_description,
            description=gog_game.description,
            header_image_url=background,
            cover_image_url=cover,
            background_image_url=background,
            screenshots=[_fix_gog_cdn_url(s) for s in (gog_game.screenshots or [])],
            release_date=gog_game.release_date,
            publishers=gog_game.publishers,
            developers=gog_game.developers,
            genres=gog_game.genres,
            categories=[],  # GOG doesn't have Steam-like categories
            tags=gog_game.tags,
        )

    def get_store_page_url(self, app_id: str) -> str:
        """Get URL to game's GOG store page"""
        db = self._get_db()
        game = db.get_game(int(app_id))
        if game and game.slug:
            return f"https://www.gog.com/game/{game.slug}"
        return f"https://www.gog.com/en/game/{app_id}"

    def get_game_metadata(self, app_id: str) -> Optional[Dict[str, Any]]:
        """Get metadata for a single game from plugin's database"""
        db = self._get_db()
        game = db.get_game(int(app_id))
        if game:
            return game.to_dict()
        return None

    def get_games_metadata_bulk(
        self, app_ids: List[str]
    ) -> Dict[str, Dict[str, Any]]:
        """Get metadata for multiple games efficiently

        Returns metadata in standardized format expected by game_service.
        """
        db = self._get_db()
        gogids = [int(app_id) for app_id in app_ids]
        result = db.get_games_metadata_bulk(gogids)

        # Convert to standardized format with string keys
        return {
            str(gogid): self._standardize_metadata(meta)
            for gogid, meta in result.items()
        }

    def _standardize_metadata(self, gog_meta: Dict[str, Any]) -> Dict[str, Any]:
        """Convert GOG metadata dict to standardized format

        Maps GOG-specific field names to the standard names expected by game_service.

        Args:
            gog_meta: Raw metadata from GogGame.to_dict()

        Returns:
            Metadata dict with standardized field names
        """
        # Build platforms list from boolean flags
        platforms = []
        if gog_meta.get("windows"):
            platforms.append("Windows")
        if gog_meta.get("mac"):
            platforms.append("macOS")
        if gog_meta.get("linux"):
            platforms.append("Linux")

        # Build per-platform release_date dict
        release_date_str = gog_meta.get("release_date", "")
        release_dates_dict: Dict[str, str] = {}
        if release_date_str:
            from luducat.plugins.sdk.datetime import parse_release_date
            parsed = parse_release_date(release_date_str)
            if parsed:
                if gog_meta.get("windows"):
                    release_dates_dict["windows"] = parsed
                if gog_meta.get("mac"):
                    release_dates_dict["macos"] = parsed
                if gog_meta.get("linux"):
                    release_dates_dict["linux"] = parsed

        # short_description: prefer description_lead, else generate from description
        short_desc = gog_meta.get("short_description", "")
        if not short_desc:
            desc_lead = gog_meta.get("description_lead", "")
            if desc_lead:
                short_desc = desc_lead
            elif gog_meta.get("description"):
                from luducat.plugins.base import generate_short_description
                short_desc = generate_short_description(gog_meta["description"])

        # Cover priority: catalog vertical > GOGdb boxart > CDN vertical crop
        cover = (
            gog_meta.get("cover_vertical_url")
            or _fix_gog_cdn_url(gog_meta.get("cover_url", ""))
        )
        if cover and _is_horizontal_gog_url(cover):
            cover = _force_vertical_cover(cover)

        # Background priority: galaxy > v0 background
        hero = (
            _fix_gog_cdn_url(gog_meta.get("galaxy_background_url", ""))
            or _fix_gog_cdn_url(gog_meta.get("background_url", ""))
        )

        # Languages — prefer localizations (richer), fallback to languages dict
        localizations = gog_meta.get("localizations") or []
        if localizations:
            supported_languages = [
                loc["name"] for loc in localizations
                if isinstance(loc, dict) and loc.get("text") and loc.get("name")
            ]
            full_audio_languages = [
                loc["name"] for loc in localizations
                if isinstance(loc, dict) and loc.get("audio") and loc.get("name")
            ]
        else:
            supported_languages = list((gog_meta.get("languages") or {}).keys())
            full_audio_languages = []

        # Features → game_modes_detail mapping
        features = gog_meta.get("features") or []
        game_modes_detail = {}
        controller_support = False
        _FEATURE_TO_MODE = {
            "single player": "Singleplayer",
            "multi-player": "Multiplayer",
            "co-op": "Co-op",
        }
        for feat in features:
            feat_lower = feat.lower() if isinstance(feat, str) else ""
            if feat_lower in _FEATURE_TO_MODE:
                game_modes_detail[_FEATURE_TO_MODE[feat_lower]] = True
            elif "controller" in feat_lower:
                controller_support = True

        # Links consolidation — build normalized list of {"type": ..., "url": ...}
        stored_links = gog_meta.get("links") or []
        # Convert list to dict for dedup/merge, then back to list
        links_dict = {entry["type"]: entry["url"] for entry in stored_links if isinstance(entry, dict) and entry.get("url")}
        slug = gog_meta.get("slug", "")
        store_link = gog_meta.get("store_link")
        if store_link:
            if store_link.startswith("/"):
                links_dict["store"] = f"https://www.gog.com{store_link}"
            else:
                links_dict["store"] = store_link
        elif slug and "store" not in links_dict:
            links_dict["store"] = f"https://www.gog.com/game/{slug}"
        forum_link = gog_meta.get("forum_link")
        if forum_link:
            links_dict["forum"] = forum_link
        support_link = gog_meta.get("support_link")
        if support_link:
            links_dict["support"] = support_link
        links_list = [{"type": k, "url": v} for k, v in links_dict.items() if v]

        # Content ratings → required_age extraction + IGDB-compatible age_ratings
        content_ratings = gog_meta.get("content_ratings") or []
        required_age = gog_meta.get("age_rating")
        age_ratings = []
        if content_ratings:
            max_age = 0
            for cr in content_ratings:
                if isinstance(cr, dict):
                    system = cr.get("name", "")
                    age = cr.get("ageRating")
                    if system and isinstance(age, (int, float)):
                        age_ratings.append({"system": system, "rating": str(int(age))})
                        if age > max_age:
                            max_age = int(age)
            if not required_age and max_age > 0:
                required_age = max_age

        return {
            "title": gog_meta.get("title", ""),
            "short_description": short_desc,
            "description": gog_meta.get("description", ""),
            "header_url": hero,
            "cover": cover,
            "hero": hero,
            "logo_url": _fix_gog_cdn_url(gog_meta.get("logo_url", "")),
            "icon_url": _fix_gog_cdn_url(gog_meta.get("icon_url", "")),
            "screenshots": [_fix_gog_cdn_url(s) for s in (gog_meta.get("screenshots") or [])],
            "release_date": release_dates_dict if release_dates_dict else release_date_str,
            "developers": gog_meta.get("developers", []),
            "publishers": gog_meta.get("publishers", []),
            "genres": gog_meta.get("genres", []),
            "features": features,
            "platforms": platforms,
            "type": gog_meta.get("type", ""),
            "slug": slug,
            "is_free": (
                gog_meta.get("is_free", False)
                or gog_meta.get("price_json", {}).get("final") == "$0.00"
            ),
            "price": gog_meta.get("price", ""),
            "rating": (gog_meta.get("rating", 0) or 0) * 2,  # GOG stars*10 → 0-100
            "supported_languages": supported_languages,
            "full_audio_languages": full_audio_languages,
            "videos": gog_meta.get("videos", []),
            # New fields
            "tags": gog_meta.get("tags", []),
            "franchise": gog_meta.get("series_name", ""),
            "required_age": required_age,
            "age_ratings": age_ratings,
            "content_ratings": content_ratings,
            "editions": gog_meta.get("editions", []),
            "game_modes_detail": game_modes_detail if game_modes_detail else {},
            "controller_support": controller_support,
            "links": links_list,
            "dlcs": gog_meta.get("dlcs", []),
            "changelog": gog_meta.get("changelog", ""),
        }

    # === UNIFORM METADATA INTERFACE ===

    def get_metadata_for_store_game(
        self,
        store_name: str,
        store_id: str,
        normalized_title: str = "",
    ) -> Optional[Dict[str, Any]]:
        """Resolve a game in GOG's catalog and return standardized metadata.

        Resolution strategy:
        1. If store_name == "gog" → direct ID lookup
        2. Otherwise → title-based search in GOG catalog
        3. Standardize field names via _standardize_metadata()
        4. API-on-cache-miss for description and screenshots

        Args:
            store_name: Store identifier
            store_id: Store's app ID
            normalized_title: Optional normalized title for cross-store search

        Returns:
            Standardized metadata dict, or None
        """
        db = self._get_db()
        game = None

        if store_name == self.store_name:
            try:
                game = db.get_game(int(store_id))
            except (ValueError, TypeError):
                pass
        if not game and normalized_title:
            game = self._find_game_record_by_title(normalized_title)

        if not game:
            return None

        metadata = self._standardize_metadata(game.to_dict())

        # API-on-cache-miss: fetch from GOG products API if key fields empty
        if not metadata.get("description") or not metadata.get("screenshots"):
            self._fetch_missing_metadata(game, metadata)

        return metadata

    def _find_game_by_title(self, normalized_title: str) -> Optional[Dict[str, Any]]:
        """Search GOG catalog by normalized title."""
        game = self._find_game_record_by_title(normalized_title)
        if not game:
            return None
        metadata = self._standardize_metadata(game.to_dict())
        if not metadata.get("description") or not metadata.get("screenshots"):
            self._fetch_missing_metadata(game, metadata)
        return metadata

    def _find_game_record_by_title(self, normalized_title: str) -> Optional[GogGame]:
        """Find a GogGame record by normalized title using lazy index."""
        if self._title_index is None:
            self._build_title_index()
        gogid = self._title_index.get(normalized_title)
        if gogid is not None:
            return self._get_db().get_game(gogid)
        return None

    def _build_title_index(self) -> None:
        """Build lazy normalized_title → gogid index from all catalog games."""
        from luducat.plugins.sdk.text import normalize_title
        self._title_index = {}
        db = self._get_db()
        for game in db.get_all_games():
            nt = normalize_title(game.title)
            if nt:
                self._title_index[nt] = game.gogid
        logger.debug(f"Built GOG title index: {len(self._title_index)} entries")

    def _fetch_missing_metadata(
        self, game: GogGame, metadata: Dict[str, Any]
    ) -> None:
        """Fetch missing description/screenshots from GOG products API.

        Updates both the metadata dict in-place and the local DB cache.
        """
        gogid = game.gogid
        url = (
            f"https://api.gog.com/products/{gogid}"
            f"?expand=description,screenshots&locale=en-US"
        )
        headers = {"User-Agent": USER_AGENT}

        try:
            resp = self.http.get(url, headers=headers, timeout=15)
            if resp.status_code != 200:
                logger.debug(
                    f"GOG products API returned {resp.status_code} for {gogid}"
                )
                return

            data = resp.json()
            db = self._get_db()
            changed = False

            # Description
            if not metadata.get("description"):
                desc_obj = data.get("description", {})
                html_desc = desc_obj.get("full", "")
                if html_desc:
                    metadata["description"] = html_desc
                    if not game.description:
                        game.description = html_desc
                        changed = True

            # Screenshots — same parsing as gog_api.py
            if not metadata.get("screenshots"):
                screenshots = []
                for ss in data.get("screenshots", []):
                    formatted = ss.get("formatted_images", [])
                    url_str = None
                    for fmt_name in ("ggvgl_2x", "ggvgl", "ggvgm_2x", "ggvgm"):
                        for fmt in formatted:
                            if fmt.get("formatter_name") == fmt_name:
                                url_str = fmt.get("image_url")
                                break
                        if url_str:
                            break
                    if not url_str and formatted:
                        url_str = formatted[0].get("image_url")
                    if url_str:
                        screenshots.append(url_str)
                if screenshots:
                    metadata["screenshots"] = screenshots
                    if not game.screenshots:
                        game.screenshots = screenshots
                        changed = True

            if changed:
                db.commit()
                logger.info(
                    f"Enriched GOG game {gogid} from products API (on-demand)"
                )

        except Exception as e:
            logger.debug(f"Failed to fetch missing GOG metadata for {gogid}: {e}")
            try:
                self._get_db().rollback()
            except Exception:
                pass

    def get_screenshots_for_app(self, app_id: str) -> List[str]:
        """Get screenshot URLs for a single app

        Args:
            app_id: GOG game ID

        Returns:
            List of screenshot URLs
        """
        db = self._get_db()
        game = db.get_game(int(app_id))
        if game and game.screenshots:
            return game.screenshots
        return []

    def get_game_description(self, app_id: str) -> str:
        """Get description for a single game, fetching from API on cache miss.

        Args:
            app_id: GOG game ID

        Returns:
            HTML description string, or empty string if not found
        """
        db = self._get_db()
        game = db.get_game(int(app_id))
        if game and game.description:
            return game.description

        # Not in local cache — try GOG products API (public, no auth needed)
        return self.refresh_game_description(app_id) or ""

    def refresh_game_description(self, app_id: str) -> Optional[str]:
        """Fetch game description from GOG products API.

        Uses the public GOG products endpoint (no authentication needed).
        Caches the result in the local DB if the game exists.

        Args:
            app_id: GOG game ID

        Returns:
            HTML description or None
        """
        gogid = int(app_id)
        url = f"https://api.gog.com/products/{gogid}?expand=description&locale=en-US"
        headers = {
            "User-Agent": USER_AGENT,
        }

        try:
            resp = self.http.get(url, headers=headers, timeout=15)
            if resp.status_code != 200:
                logger.debug(f"GOG products API returned {resp.status_code} for {gogid}")
                return None

            data = resp.json()
            desc_obj = data.get("description", {})
            html_description = desc_obj.get("full")
            if not html_description:
                return None

            # Cache in local DB if game exists
            db = self._get_db()
            game = db.get_game(gogid)
            if game and not game.description:
                game.description = html_description
                db.commit()
                logger.info(f"Updated description for GOG game {gogid} from products API")

            return html_description

        except Exception as e:
            logger.debug(f"Failed to fetch GOG description for {gogid}: {e}")
            try:
                self._get_db().rollback()
            except Exception:
                pass
            return None

    def on_sync_complete(self, progress_callback=None) -> Dict[str, Any]:
        """Called after sync completes (synchronous hook)"""
        return {}

    async def on_sync_complete_async(
        self,
        progress_callback=None,
        cancel_check=None,
    ) -> Dict[str, Any]:
        """Async post-sync hook: enrich owned games via GOG products API.

        Enriches ALL unenriched owned games in one pass with full metadata
        (description, screenshots, downloads, changelog, DLCs, languages,
        videos).
        """
        if not self.is_authenticated():
            return {}

        db = self._get_db()
        api = self._get_api_client()

        # Get owned game IDs that haven't been enriched yet
        owned_ids = db.get_all_gogids(include_dlc=False)
        unenriched = db.get_unenriched_owned_gogids(owned_ids)

        if not unenriched:
            return {}

        total = len(unenriched)

        if progress_callback:
            progress_callback(
                f"Fetching metadata for {total} games...", 0, total
            )

        enriched = 0
        errors = 0
        for idx, gogid in enumerate(unenriched, 1):
            if cancel_check and cancel_check():
                break

            if progress_callback:
                game = db.get_game(gogid)
                name = game.title if game else str(gogid)
                progress_callback(name, idx, total)

            try:
                metadata = await api.get_product_metadata(gogid)
                if metadata:
                    existing = db.get_game(gogid)
                    if existing:
                        self._apply_products_api_data(existing, metadata)
                        db.commit()
                        enriched += 1
                else:
                    errors += 1
            except Exception as e:
                logger.warning(f"Failed to enrich GOG game {gogid}: {e}")
                db.rollback()
                errors += 1

        if enriched:
            logger.info(
                f"GOG products API enrichment: {enriched}/{total} enriched, "
                f"{errors} errors"
            )

        return {
            "gog_enriched": enriched,
            "gog_enrich_errors": errors,
        }

    def get_install_sync_data(self) -> Optional[Dict[str, Any]]:
        """Return installation status for GOG games.

        On Windows: queries GOG Galaxy's local database for all installed games.
        On Linux: returns None (Heroic detection deferred to SDK phase).

        Returns:
            Dict mapping gogid -> {"installed": True, "install_path": str|None}
            for installed games only, or None if not supported.
        """
        if not self.has_local_data_consent():
            logger.debug("Skipping GOG install sync: local data consent not granted")
            return None

        try:
            result = _galaxy_get_installed()
            if result:
                logger.info(f"GOG install sync: {len(result)} installed games detected")
            return result
        except Exception as e:
            logger.warning(f"Failed to get GOG installed games: {e}")
            return None

    def get_playtime_sync_data(self) -> Optional[Dict[str, Any]]:
        """Return playtime data from GOG Galaxy's local database.

        On Windows: reads GameTimes + LastPlayedDates from Galaxy 2.0 DB.
        On Linux: returns None (Galaxy is Windows-only).

        Returns:
            Dict mapping gogid -> {"minutes": int, "last_played": str|None}
            or None if not available.
        """
        if not self.has_local_data_consent():
            logger.debug("Skipping GOG playtime sync: local data consent not granted")
            return None

        try:
            result = _galaxy_get_playtime()
            if result:
                logger.info(f"GOG playtime sync: {len(result)} games with playtime")
            return result
        except Exception as e:
            logger.warning(f"Failed to get GOG playtime data: {e}")
            return None

    def get_tag_sync_data(self) -> Optional[Dict[str, Any]]:
        """Return GOG user tag and favorite mappings for game_service to apply.

        GOG's "FAVORITE" tag maps to luducat's native is_favorite flag.
        Other user tags map to luducat UserTag entries.

        Returns:
            Dict with "mode" and "mappings", or None if tag sync disabled
        """
        db = self._get_db()

        # Query all GOG games that have user_tags set
        from .database import GogGame as GogGameModel
        from sqlalchemy import and_

        games_with_tags = db.session.query(GogGameModel).filter(
            and_(
                GogGameModel._user_tags.isnot(None),
                GogGameModel._user_tags != "[]",
            )
        ).all()

        if not games_with_tags:
            return None

        mappings = {}
        for game in games_with_tags:
            tags = game.user_tags  # List[str] from JSON property
            if not tags:
                continue

            # Separate FAVORITE from regular tags
            is_favorite = "FAVORITE" in tags
            regular_tags = [t for t in tags if t != "FAVORITE"]

            mappings[str(game.gogid)] = {
                "tags": regular_tags,
                "favorite": is_favorite,
            }

        if not mappings:
            return None

        return {
            "mode": "add_only",
            "mappings": mappings,
        }

    def get_catalog_stats(self) -> Dict[str, int]:
        """Get catalog statistics

        Returns:
            Dict with game_count, dlc_count, etc.
        """
        db = self._get_db()
        return {
            "game_count": db.get_game_count(include_dlc=False),
            "total_count": db.get_game_count(include_dlc=True),
        }

    def needs_gogdb_import(self) -> Tuple[bool, str]:
        """Check if GOGdb import is needed before sync

        Import is needed if:
        - No games in catalog (never imported)
        - Most recent game was imported more than IMPORT_FRESHNESS_DAYS ago

        Returns:
            Tuple of (needs_import: bool, reason: str)
        """
        db = self._get_db()
        game_count = db.get_game_count(include_dlc=False)

        if game_count == 0:
            return True, "GOGdb catalog is empty. Please import the GOGdb database first."

        # Check freshness of most recent import
        from datetime import timedelta

        # Get most recently updated game
        most_recent = db.session.query(GogGame).order_by(
            GogGame.last_updated.desc()
        ).first()

        if most_recent and most_recent.last_updated:
            age = utc_now() - most_recent.last_updated
            if age > timedelta(days=IMPORT_FRESHNESS_DAYS):
                days_old = age.days
                return True, (
                    f"GOGdb catalog is {days_old} days old. "
                    f"Please update the GOGdb database import."
                )

        return False, ""

    def _has_gogdb_data(self) -> bool:
        """Check if any GOGdb-imported games exist in catalog.db."""
        db = self._get_db()
        row = db.session.query(GogGame.gogid).filter(
            GogGame.gogdb_imported == True,  # noqa: E712
        ).first()
        return row is not None

    def check_sync_prerequisites(self) -> None:
        """Check if sync can proceed, raise if not.

        When authenticated, GOGdb import is optional — the GOG API provides
        full metadata for owned games. GOGdb is only required when not
        authenticated (catalog browsing only).

        On first authenticated sync with no GOGdb data, raises
        GogdbImportRecommended so the UI can prompt the user.

        Raises:
            GogdbImportRequired: If GOGdb import is needed and user is not authenticated
            GogdbImportRecommended: First authenticated sync without GOGdb data
        """
        if self.is_authenticated():
            # Check if first sync without GOGdb data
            if not self._has_gogdb_data():
                # Only prompt once — check config flag
                from luducat.plugins.sdk.config import get_config_value, set_config_value
                if not get_config_value("gog.gogdb_import_offered", False):
                    set_config_value("gog.gogdb_import_offered", True)
                    raise GogdbImportRecommended(
                        "For best results (vertical covers, richer metadata), "
                        "import the GOGdb database before your first sync.\n\n"
                        "You can skip this and sync now — games will still appear "
                        "but with lower-quality covers. You can import GOGdb "
                        "later from the GOG plugin settings."
                    )
            return

        needs_import, reason = self.needs_gogdb_import()
        if needs_import:
            raise GogdbImportRequired(reason)

    def import_from_gogdb(
        self,
        progress_callback: Optional[Any] = None
    ) -> Dict[str, Any]:
        """Import games from GOGdb dump

        Downloads the latest GOGdb dump and imports new games.

        Args:
            progress_callback: Function(phase, current, total) for updates

        Returns:
            Stats dict with import results
        """
        importer = GogdbImporter(self.data_dir, self.cache_dir, http_client=self.http)
        return importer.import_from_gogdb(progress_callback)

    def close(self) -> None:
        """Clean up resources"""
        if self._db:
            self._db.close()
            self._db = None
        self._api_client = None
        logger.debug("GOG plugin closed")

    def on_enable(self) -> None:
        """Called when plugin is enabled.

        Ensures the GOG catalog database exists so that on-demand
        metadata lookups don't fail before the first sync.
        """
        logger.info("GOG plugin enabled")
        try:
            self._get_db()
        except Exception as e:
            logger.debug(f"GOG DB init in on_enable: {e}")

    def on_disable(self) -> None:
        """Called when plugin is disabled"""
        logger.info("GOG plugin disabled")
        self.close()
